apiVersion: v1
kind: Service
metadata:
  name: vault-ansible-vault-api
  namespace: vault-ansible
spec:
  selector:
    app.kubernetes.io/name: ubuntu-deployment-vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200