apiVersion: v1
kind: Service
metadata:
  name: vault-cluster-api-dr
  namespace: vault-dr
spec:
  selector:
    app.kubernetes.io/name: vault-dr
  ports:
    - protocol: TCP
      port: 8201
      targetPort: 8201