apiVersion: v1
kind: Service
metadata:
  name: vault-cluster-api-primary
  namespace: vault-primary
spec:
  selector:
    app.kubernetes.io/name: vault-primary
  ports:
    - protocol: TCP
      port: 8201
      targetPort: 8201