---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-vault-dr
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: app-vault-dr
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy Vault
  destinations:
    - namespace: vault-dr
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://charts.adfinis.com
    - https://helm.releases.hashicorp.com
