---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: caasperli
  namespace: infra-argocd
spec:
  description: deploy caasperli
  destinations:
    - namespace: caasperli
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://charts.adfinis.com

