---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc-apps
  namespace: infra-argocd
spec:
  destination:
    namespace: infra-argocd
    server: https://kubernetes.default.svc
  project: infra-argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: misc-apps
    repoURL: https://charts.adfinis.com
    targetRevision: "*"
    helm:
      values: |
        fullnameOverride: app
        argocdApps:
          enabled: true
          project: infra-argocd
          syncPolicy:
            automated: {}
            syncOptions:
              - CreateNamespace=true
          destination:
            server: https://kubernetes.default.svc
            namespace: infra-argocd
          values:
            applications:
              - name: argocd-configs
                namespace: infra-argocd
                project: infra-argocd
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/
                  repoURL: https://github.com/Xelef2000/HC-Vault-Boost-argocd-configs.git
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}
                  syncOptions:
                    - CreateNamespace=true
              - name: namespaces
                namespace: infra-argocd
                additionalLabels:
                  app.kubernetes.io/component: infra
                  app.kubernetes.io/name: helm-infrastructure-argoconfig
                project: namespaces
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/namespaces/
                  repoURL: https://github.com/Xelef2000/HC-Vault-Boost-argocd-configs.git
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}
              - name: appprojects
                namespace: infra-argocd
                additionalAnnotations:
                  argocd.argoproj.io/sync-wave: "-1"
                project: appprojects
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/appprojects/
                  repoURL: https://github.com/Xelef2000/HC-Vault-Boost-argocd-configs.git
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}
              - name: services
                # namespace: infra-argocd
                additionalLabels:
                  app.kubernetes.io/component: infra
                  app.kubernetes.io/name: helm-infrastructure-argoconfig
                project: services
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/services/
                  repoURL: https://github.com/Xelef2000/HC-Vault-Boost-argocd-configs.git
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}


